#document settings
title: Project Open Data
desc: "Open Data Policy â€” Managing Information as an Asset"
url: //project-open-data.cio.gov/
repo_name: project-open-data.github.io
branch: master

#global settings, no need to change these
root_url: //project-open-data.cio.gov
org_name: project-open-data

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false
