#document settings
title: Federal Spending Transparency
desc: "DATA Act and FFATA Collaboration Space"
url: //fedspendingtransparency.github.io/
repo_name: fedspendingtransparency.github.io
branch: master

#global settings, no need to change these
root_url: //fedspendingtransparency.github.io
org_name: fedspendingtransparency

# default build settings for running locally, no need to edit
highlighter: rouge
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "LICENSE"]
markdown: kramdown
relative_permalinks: false
